name: Build APK YURXZ REJOIN

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: kivy/buildozer:latest

    steps:
      - uses: actions/checkout@v4

      - name: Build APK
        run: |
          yes | buildozer android debug 2>&1 | tee build_log.txt
          find . -name "*.apk" 2>/dev/null

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: YURXZ-REJOIN-APK
          path: bin/*.apk
          if-no-files-found: warn

      - name: Upload log jika gagal
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build_log.txt
